### ISSUE TITLE
Add tests against performance regressions

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2211]
Currently we have no way to track when we introduced performance regressions. There are two ways we can use to address this:

1. Simple micro-benchmarks for each library function. These can use a set of automatically generated but fixed routes on a _real_ dataset.
   - Problem: Dataset will be small (e.g. Monaco), so no cross-country routes as baseline
   - Will only give a quantitative measurement between changes (e.g. did we make it worse?)

2. Simple integration benchmarks:
  - How long does it take to prepare the test dataset?
  - How long does it take to contract the test dataset?
  - How long does it take to run a fixed set of queries against the server?

I think we should do both. (2) is a little bit easier since we already do most of this on the demo server. All it needs its some glue to take timings and print them pretty on travis.

For (1) I want to use https://github.com/google/benchmark for:
- [ ] Route
- [ ] Match
- [ ] Trip
- [ ] Nearest

**Comment by TheMarex** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/2216 addresses (2). I'm not sure if this should be moved to cucumber eventually. My main concern is that containing timings is not really portable: It will wary widely from platform to platform.

**Comment by TheMarex** [comment]
Current preliminary findings using (2):

`rewrite/new-api` is about factor two slower than develop. While API overhead becomes significant for request > 10k, what dominates is mostly finding the entry points into the road network (also known as "generating the phantom nodes").

![ms_boxplot](https://cloud.githubusercontent.com/assets/606968/14324427/0a1f7328-fc25-11e5-8f76-b993c4498f32.png)

This is only on monaco, hence it maxes out at 10km range.

**Comment by TheMarex** [comment]
The `rtree-bench` shows that rtree queries got more than factor two slower. Using git-bisect I was able to fin the commit that causes it:

50738f8ce09193f13fd5ce03c20a87e80c28c395

Seems like this causes a regression in one of the math functions.

**Comment by daniel-j-h** [comment]
@TheMarex if your benchmarking scripts for the plot above are somewhat re-usable I would love if you could share them / put into version control, for when situations like this arise in the future.

**Comment by TheMarex** [comment]
Re-did the benchmarks on an actual `r3.4xlarge` on the planet (but queries US only to sidestep the `NoRoute` cross-atlantic queries). All optimization are all in `makeitfaster`.

### Before StaticRTree leaf optimizations, StaticRTree leaf size 1024 objects per leaf

- Don't have a fancy graph here, as you can see above even on Monaco we were hitting between 4 and 8 ms for getting the phantom nodes

### Without simplification optimizations, StaticRTree leaf size 128 objects per leaf

![ms_boxplot_old](https://cloud.githubusercontent.com/assets/606968/14357308/7eac4cf2-fce8-11e5-807d-3c61a1c001b9.png)

### With optimizations

![ms_boxplot_new](https://cloud.githubusercontent.com/assets/606968/14357349/a2876bf2-fce8-11e5-8b38-c76f5574b4be.png)

### Todo

- [ ] Graphs for `table` plugin w.r.t `#coordinates`
- [ ] Redo all measurements on `4.9.1` and `develop` to get more context (requires data update -> will take each 8 hours to setup)
- [ ] Split up optimizations into atomic commits
- [ ] Merge into `rewrite/new-api`

**Comment by TheMarex** [comment]
Further graph:

### `makeitfast`, `/table` service on US by number of waypoints

![ms_boxplot_table_new](https://cloud.githubusercontent.com/assets/606968/14365016/cd0bcbf2-fd0b-11e5-96d3-dd8f61962c6b.png)

### `makeitfast`, `/route` service on DC by number of waypoints, `steps=false`

![ms_boxplot_route_new](https://cloud.githubusercontent.com/assets/606968/14365055/f9dd1118-fd0b-11e5-9c34-bfb459039947.png)

### `makeitfast`, `/route` service on DC by number of waypoints, `steps=true`

![ms_boxplot_full_route_new](https://cloud.githubusercontent.com/assets/606968/14365060/014db0a6-fd0c-11e5-8881-a51012399c3b.png)

All measurements have been take on the same planet dataset as above with RTree optimizations.

**Comment by TheMarex** [comment]
### 4.9.0 `/viaroute` sevice on US by route distance

![ms_boxplot_491](https://cloud.githubusercontent.com/assets/606968/14390555/fbaf031e-fdb7-11e5-89ef-f151f1954f12.png)

### Comparison `4.9.1` and `makeitfaster`

This shows a comparison of the same requests on US, by distance on `makeitfast` (left) and `4.9.1` (right). We are a little bit fast on long queries.

![ms_boxplot_491_and_makeitfast](https://cloud.githubusercontent.com/assets/606968/14390486/a45fbcac-fdb7-11e5-98e3-30b1a7e04086.png)

**Comment by TheMarex** [comment]
To get a better sense of the ceiling we hit when doing StaticRTree leaf size optimizations, I also tried 128 elements per leaf:

(routes on DC, without geometry, `makeitfaster`)

![ms_boxplot_route_new_128](https://cloud.githubusercontent.com/assets/606968/14404443/fc023056-fe76-11e5-8c2b-cd2b8cef42a0.png)

As you can see its slightly slower than the 256 elements per leaf version. So with `256` we seem near a local optimum, which is fine for our purposes.

**Comment by TheMarex** [comment]
Closing in favor of #2258.
