### ISSUE TITLE
Revisit Merging of Segregated Roads/Joining Road Adjustments

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3107]
We should refactor the code in the intersection generator [here](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_generator.cpp#L184-L480). 

When https://github.com/Project-OSRM/osrm-backend/pull/2779 gets merged, the angle offsets chosen here might not be as relevant anymore.
## Tasks
- [x] create map that shows locations where merging triggers (see https://github.com/Project-OSRM/osrm-backend/pull/3170)
- [ ] compare turn angles at these locations
- [ ] revisit merging criteria (canMerge)
- [ ] remove own angle computations (rely on intersection-classification/coordinate extractor)
- [ ] general refactor

In a related task, we should also take a look at:
[merging at destination](https://github.com/Project-OSRM/osrm-backend/blob/3f0f0e306b3c2ee5eada6512c3ce3ab00b1b0460/src/extractor/guidance/intersection_generator.cpp#L502-L565).

**Comment by MoKob** [comment]
Issues found in looking at the debug map:

Hohenzollernbrücke should not get merged OSM: http://www.openstreetmap.org/#map=18/52.48767/13.30016&layers=C

Gustav Müller Platz is a false merge: http://www.openstreetmap.org/#map=18/52.48337/13.36184&layers=C

Lietzenburger Straße is a false positive
http://www.openstreetmap.org/#map=18/52.49950/13.33916&layers=C
