### ISSUE TITLE
Prepare list of deprecated API parameters/values for `6.0` release

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3298]
We deprecated some API parameters/values over the 5.x live-cycle and need to prepare for the 6.x cleanup.

Off the top of my head the following things are marked for removal:

- [ ] `StepManeuver.bearing_before` and `StepManeuver.bearing_after` (replaced by `RouteStep.intersections`)
- [ ] `StepManeuver.location` (replaced by `RouteStep.intersections`)
- [ ] `StepManeuver.type = "ramp"` (replaced by `on ramp` and `off ramp`)
- [ ] Using `bearings=` without `radiuses=` per https://github.com/Project-OSRM/osrm-backend/issues/2983
- [ ] Specifying a `bearings` range per https://github.com/Project-OSRM/osrm-backend/issues/2983

Any more things that come to mind @MoKob @daniel-j-h @danpat @freenerd?

**Comment by daniel-j-h** [comment]
libosrm API:
- https://github.com/Project-OSRM/osrm-backend/pull/2941
- https://github.com/Project-OSRM/osrm-backend/pull/2991
- potentially moving away from the JSON variant

**Comment by MoKob** [comment]
- [ ] roundabout instruction -> enter roundabout + exit roundabout
- [ ] direction_modifier u-turn -> invalid + new turn type u-turn

**Comment by TheMarex** [comment]
@MoKob can you link the tickets for those here? I'm missing some context here.

**Comment by MoKob** [comment]
Also:
 - [ ] valid per indication https://github.com/Project-OSRM/osrm-backend/issues/2935

**Comment by daniel-j-h** [comment]
- [ ] Switch from always generating hint to hints on demand https://github.com/Project-OSRM/osrm-backend/pull/3456

**Comment by karenzshea** [comment]
- [ ] Remove redundant boolean based parameter for annotations in RouteParameters https://github.com/Project-OSRM/osrm-backend/issues/3644

**Comment by freenerd** [comment]
- [ ] Remove geojson responses and go polyline only https://github.com/Project-OSRM/osrm-backend/issues/3752

**Comment by TheMarex** [comment]
- [ ] Remove `--generate-edge-lookup` parameter from `osrm-{contract,customize}` as it does nothing now

**Comment by daniel-j-h** [comment]
- [ ] In https://github.com/Project-OSRM/osrm-backend/pull/4047 I implemented an `alternatives=n` overload in addition to `alternatives=true/false`. With v6 the boolean overload should go. Needs adaption in route parameters, route parameters grammar and viaroute plugin callsite.

**Comment by hannesaddec** [comment]
Can you confirm that the hint parameter got removed in v6.0

**Comment by DennisOSRM** [comment]
It's not removed yet
